version: '3.8'

services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        environment:
            - SECRET_KEY=$$^as&bi4a5ho^j$$dm3!=hm=)hbv_el5uoa2^ivl^6!ylab_$$&^
            - DEBUG=1
            - API_KEY=4fcb0f2189f50a1628486b38d53b65f7
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: postgres:13
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/

volumes:
    postgres_data:
